import React from "react";
import { useAppSelector, useAppDispatch } from "@/hooks/useRedux";
import { closeModal } from "@/store/slices/uiSlice";
import { Bot, Copy, Check, X, Sparkles } from "lucide-react";
import { Chip } from "@/components/ui/Chip";
import styles from "./EnrichmentSuccessModal.module.css";

export const EnrichmentSuccessModal: React.FC = () => {
  const dispatch = useAppDispatch();
  const isOpen = useAppSelector((state) => state.ui.modals.enrichmentSuccess);
  const aiResult = useAppSelector((state) => state.ui.aiResult);
  const [copied, setCopied] = React.useState(false);

  if (!isOpen || !aiResult) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(aiResult.email);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className={styles.overlay}>
      <div className={styles.modal}>
        <div className={styles.header}>
          <div className={styles.titleWithIcon}>
            <div className={styles.iconWrapper}>
              <Sparkles size={20} className={styles.sparklesIcon} />
            </div>
            <div>
              <h3>AI Enrichment Complete</h3>
              <p className={styles.subtitle}>Generated personalized outreach</p>
            </div>
          </div>
          <button
            className={styles.closeBtn}
            onClick={() => dispatch(closeModal("enrichmentSuccess"))}
          >
            <X size={20} />
          </button>
        </div>

        <div className={styles.content}>
          <div className={styles.contextCard}>
            <div className={styles.cardHeader}>
              <Bot size={16} className={styles.botIcon} />
              <span>AI Context & Reasoning</span>
            </div>
            <div className={styles.contextGrid}>
              <div className={styles.contextItem}>
                <span className={styles.label}>Prospect Company</span>
                <span className={styles.value}>{aiResult.company}</span>
              </div>
              <div className={styles.contextItem}>
                <span className={styles.label}>Recipient</span>
                <span className={styles.value}>{aiResult.person}</span>
              </div>
              <div className={styles.contextItem}>
                <span className={styles.label}>Strategy</span>
                <span className={styles.value}>Value-based outbound</span>
              </div>
            </div>
            <div className={styles.aiBadge}>
              <Sparkles size={12} />
              <span>Generated by Llama 3.3-70b</span>
            </div>
          </div>

          <div className={styles.resultSection}>
            <div className={styles.resultHeader}>
              <h4>Generated Email</h4>
              <button
                className={`${styles.copyBtn} ${copied ? styles.copied : ""}`}
                onClick={handleCopy}
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? "Copied!" : "Copy to Clipboard"}
              </button>
            </div>
            <div className={styles.emailPreview}>
              {aiResult.email.split("\n").map((line, i) => (
                <p key={i}>{line || "\u00A0"}</p>
              ))}
            </div>
          </div>
        </div>

        <div className={styles.footer}>
          <p className={styles.demoNote}>
            <strong>Note:</strong> This is an AI-generated draft. Please review
            before sending.
          </p>
          <div className={styles.actions}>
            <button
              className={styles.secondaryBtn}
              onClick={() => dispatch(closeModal("enrichmentSuccess"))}
            >
              Close
            </button>
            <button
              className={styles.primaryBtn}
              onClick={() => {
                handleCopy();
                dispatch(closeModal("enrichmentSuccess"));
              }}
            >
              Copy & Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
